require("user.packer")
require("user.colorschemes.catppuccin")
require("user.plugins.impatient")
require("user.settings")
require("user.mappings")
require("user.autocommands")
require("user.lsp")
require("user.plugins.autopairs")
require("user.plugins.cinnamon")
require("user.plugins.colorizer")
require("user.plugins.comment")
require("user.plugins.dashboard")
require("user.plugins.fidget")
require("user.plugins.gitsigns")
require("user.plugins.illuminate")
require("user.plugins.indent")
require("user.plugins.jabs")
require("user.plugins.lspsaga")
-- require("user.plugins.lualine")
require("user.plugins.feline")
require("user.plugins.navic")
require("user.plugins.neoclip")
require("user.plugins.nvimtree")
require("user.plugins.session")
require("user.plugins.surround")
require("user.plugins.telescope")
require("user.plugins.todo")
require("user.plugins.toggleterm")
require("user.plugins.treesitter")
require("user.plugins.winbar")
require("user.plugins.whichkey")
-- require("user.plugins.twilight")
-- require("user.plugins.zen")
-- require("user.plugins.discord")
