return {
	{
		"glepnir/dashboard-nvim",
		event = "VimEnter",
		opts = {
			theme = "doom",
			config = {
				header = {
					[[                                                                   ]],
					[[                                                                   ]],
					[[ ██████   █████                                ███                 ]],
					[[░░██████ ░░███                                ░░░                  ]],
					[[ ░███░███ ░███   ██████   ██████  █████ █████ ████  █████████████  ]],
					[[ ░███░░███░███  ███░░███ ███░░███░░███ ░░███ ░░███ ░░███░░███░░███ ]],
					[[ ░███ ░░██████ ░███████ ░███ ░███ ░███  ░███  ░███  ░███ ░███ ░███ ]],
					[[ ░███  ░░█████ ░███░░░  ░███ ░███ ░░███ ███   ░███  ░███ ░███ ░███ ]],
					[[ █████  ░░█████░░██████ ░░██████   ░░█████    █████ █████░███ █████]],
					[[░░░░░    ░░░░░  ░░░░░░   ░░░░░░     ░░░░░    ░░░░░ ░░░░░ ░░░ ░░░░░ ]],
					[[                                                                   ]],
					[[                                                                   ]],
				},
				center = {
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "New File                                            ",
						desc_hl = "String",
						key = "n",
						key_hl = "Constant",
						keymap = "SPC f n",
						action = "enew",
					},
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "Find File                                           ",
						desc_hl = "String",
						key = "f",
						key_hl = "Constant",
						keymap = "SPC f f",
						action = "Telescope find_files",
					},
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "Recent Files                                        ",
						desc_hl = "String",
						key = "r",
						key_hl = "Constant",
						keymap = "SPC f r",
						action = "Telescope oldfiles",
					},
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "Configuration                                       ",
						desc_hl = "String",
						key = "c",
						key_hl = "Number",
						keymap = "SPC f c",
						action = "cd ~/.config/nvim | e $MYVIMRC",
					},
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "Sync Plugins                                        ",
						desc_hl = "String",
						key = "s",
						key_hl = "Constant",
						keymap = "SPC p s",
						action = "Lazy sync",
					},
					{
						icon = "   ",
						icon_hl = "Title",
						desc = "Quit Neovim                                         ",
						desc_hl = "String",
						key = "q",
						key_hl = "Constant",
						keymap = "SPC q q",
						action = "qa",
					},
				},
			},
		},
		dependencies = { { "nvim-tree/nvim-web-devicons" } },
	},
}
